name: Setup Node.js
description: Setup Node.js environment

runs:
    using: composite
    steps:
        - uses: actions/setup-node@v6
          with:
              node-version: 24
              cache: npm
        - shell: bash
          run: npm ci
