[package]
name = "website"
version = "0.0.0-alpha.0"
authors = ["Javier E. <jaedns@gmail.com>"]
edition = "2024"

[dependencies]
dioxus = { version = "0.7.0-rc.0", features = ["router"] }
sdk = { git = "https://github.com/mangocubed/sdk.git", tag = "v0.0.0-alpha.0", default-features = false }

[features]
default = ["web"]
web = ["dioxus/web"]
