name: Deploy on GitHub Pages

on:
    release:
        types: [published]

    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
    # Build job
    build:
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v4
            - uses: actions/configure-pages@v5
            - uses: ./.github/actions/setup-dioxus
            - uses: ./.github/actions/setup-node
            - run: npm run build
            - run: dx bundle --web --release
            - uses: actions/upload-pages-artifact@v3
              with:
                  path: ./target/dx/website/release/web/public

    # Deployment job
    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-24.04
        needs: build
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
